/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_processmining_ebi_CallEbi */

#ifndef _Included_org_processmining_ebi_CallEbi
#define _Included_org_processmining_ebi_CallEbi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_processmining_ebi_CallEbi
 * Method:    call_ebi_internal
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_processmining_ebi_CallEbi_call_1ebi_1internal
  (JNIEnv *, jclass, jstring, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
